[project]
name = "post-race-analysis"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.11.0",
    "numpy>=1.21.0",
    "openai==1.91",
    "pandas>=1.5.0",
    "pydantic-ai[anthropic]>=0.0.14",
    "python-dotenv>=0.19.0",
    "requests>=2.28.0",
]
